version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8011
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Persist the SQLite database
    ports:
      - "8011:8011"
